name: Container
on: push

jobs:
  job1:
    name: On Node
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Step with docker
        uses: docker://node:12.14.1-alpine3.10 #このステップだけで起動するコンテナイメージ
        with:
          entrypoint: '/bin/echo' #コンテナ起動時にechoコマンドを実行
          args: 'Hello World' #echoコマンドの引数
      -
        name: Log node version
        run: |
          node -v #nodeバージョンの確認
          cat /etc/os-release #Linuxバージョンの確認